[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"

[rpc_endpoints]
celo-mainnet = "https://forno.celo.org"
celo-sepolia = "https://alfajores-forno.celo-testnet.org"

[etherscan]
celo-mainnet = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
celo-sepolia = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }